export const SENSORS_REQUEST_SAGA = 'SENSORS_REQUEST_SAGA';
export const SENSORS_REQUEST = 'SENSORS_REQUEST';
export const SENSORS_SUCCESS = 'SENSORS_SUCCESS';
export const SENSORS_ERROR = 'SENSORS_ERROR';

export const SENSOR_UPDATE = 'SENSOR_UPDATE';
export const SENSOR_CREATE = 'SENSOR_CREATE';
export const SENSOR_DELETE = 'SENSOR_DELETE';
export const SENSOR_DELETE_SUCCESS = 'SENSOR_DELETE_SUCCESS';
export const SENSOR_DELETE_SAGA = 'SENSOR_DELETE_SAGA';
export const SENSOR_DELETE_ERROR = 'SENSOR_DELETE_ERROR';